/*
 * Copyright (c) Bill Wixted.  All rights reserved.  
 * The software in this package is published under the terms of the MIT
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package com.referrercounter;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * <code>ReferrerServlet</code> Provides the main servlet entry point for the 
 * <code>ReferrerCounter</code> service. The page generated by this servlet 
 * displays helpful links to the service endpoints and user interfaces provided
 * in this service.
 * @author Bill
 */
@WebServlet(name = "ReferrerServlet", urlPatterns = {"/"})
public class ReferrerServlet extends HttpServlet {

    private PrintWriter out = null;
    
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        response.setContentType("text/html;charset=UTF-8");
        out = response.getWriter(); 
        
        HtmlHelper htmlHelper = new HtmlHelper(out);
        htmlHelper.printHeaders("Referrer Counter Service");
     
        print("<div>This service provides tracking of the domains found in referring URLs");
        print("<h3>Service Endpoints</h3>");
        print("<ul><li>Track Referrer Domain: <a href=\"/ReferrerCounter/TrackReferrerDomain\">/ReferrerCounter/TrackReferrerDomain</a>");
        print("<li>Top 3 Referrer Domains: <a href=\"/ReferrerCounter/Top3Domains\">/ReferrerCounter/Top3Domains</a></ul>");  
        print("<sub>Example: # curl http://localhost:8080/ReferrerCounter/TrackReferrerDomain?url=http://www.google.com/search</sub>");             
        print("<h3>Service User Interface</h3>");
        print("<ul><li>Top 3 Referrer Domains : <a href=\"/ReferrerCounter/Top3DomainsPage\">/ReferrerCounter/Top3DomainsPage</a>"); 
        print("<li>All Referrer Domains : <a href=\"/ReferrerCounter/AllDomains\">/ReferrerCounter/AllDomains</a>");
        print("<li>Referrer Domain Count Lookup: <a href=\"/ReferrerCounter/LookupUrl\">/ReferrerCounter/LookupUrl</a></ul>");

        print("</div>");
        htmlHelper.printFooters();
    }
    
    private void print(String msg) {
        out.println(msg);
    }
    
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
